### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ondrejbudai** [containerbuildsystem/cachi2#604]
Hi,

is there a release schedule? I would love to use cachi2 with Go 1.22, but the latest version 0.9.1 doesn't support it. The support was added in #591 but this PR is not released yet. This is actually quite pressing because Go 1.23 is now released, which means that Go 1.21 is no longer supported upstream. Thanks!

**Comment by eskultety** [comment]
We released preliminary support for 1.22 in https://github.com/containerbuildsystem/cachi2/releases/tag/0.10.0, closing as resolved.
