### ISSUE TITLE
Allow users to create virtual environment using any Python version

### ISSUE THREAD

**Issue by slimreaper35** [containerbuildsystem/cachi2#623]
Developers/contributors cannot automatically create `venv` using any Python version they want.
They have to do it manually.  Remove this limitation. 
Steps:

- revert https://github.com/containerbuildsystem/cachi2/commit/4fba58c635a43a7e2d648dd7e359900204cb64e0
- update [Makefile](https://github.com/containerbuildsystem/cachi2/blob/main/Makefile)
- improve [virtual-environment](https://github.com/containerbuildsystem/cachi2?tab=readme-ov-file#virtual-environment) section in README.md

**Comment by eskultety** [comment]
Resolved by: https://github.com/containerbuildsystem/cachi2/pull/633/commits/9639d8204a146c5598a6cdcd758438e3ba2318c5
