### ISSUE TITLE
The project defines both Makefile and tox.ini

### ISSUE THREAD

**Issue by a-ovchinnikov** [containerbuildsystem/cachi2#662]
The project defines both Makefile and tox.ini; in the scope of Cachi2 development both tools have similar capabilities and half of the time make works as a thin wrapper for tox. Since tox is a [development automation tool](https://www.seanh.cc/2018/09/01/tox-tutorial/) and is more native to Python ecosystem than make I propose to remove Makefile and use tox for all development automation.

**Comment by ben-alkov** [comment]
I thought about it a bit, after you asked yesterday...

*Assuming* that I understand correctly (please excuse any inaccuracies/mistakes):

- tox environments are ephemeral[1] and machine-readable, not really meant for human consumption
- OTOH, the venv created by `make` is meant to be a properly configured dev environment for humans (i.e. cachi2 is installed using the `-e` flag along with all required and dev dependencies) for e.g. running tests by hand using the `cachi2` command, or running inside Python source debuggers

Hope this helps!

[1] e.g. tox updates/rebuilds envs *seemingly* based on its current mood
